In [123]:
def feed_forward(x,y):
    
    w1 = np.random.randn()
    w2 = np.random.randn()
    w3 = np.random.randn()
    w4 = np.random.randn()
    w5 = np.random.randn()
    w6 = np.random.randn()
    w7 = np.random.randn()
    w8 = np.random.randn()
    w9 = np.random.randn()
    w10 = np.random.randn()
    b1 = np.random.randn()
    b2 = np.random.randn()
    b3 = np.random.randn()
    b4 = np.random.randn()
    b5 = np.random.randn()
    b6 = np.random.randn()
    x1 = x2 = x
    y1 = y2 = y
    a1 = w1*x1 + w2*x2 + b1
    h1 = sig_activation(a1)
    a2 = w3*y1 + w4*y2 + b2
    h2 = sig_activation(a2)
    a3 = w5*h1 + w6*h2 + b3
    h3 = sig_activation(a3)
    a4 = w6*h3 + b4
    h4 = sig_activation(a4)
    a5 = w7*h4 + b5
    h5 = sig_activation(a5)
    a6 = w8*h5 + b6
    h6 = sig_activation(a6)
    return h6
    
def sig_activation(x):
    a = 1.0/(1.0 + np.exp(-x))
    return a
    
def call_output():
    arr1= np.random.randint(1,10,5)
    arr2= np.random.randint(1,10,5)
    output = []
    for x,y in zip(arr1,arr2):
        op = feed_forward(x,y)
        output.append(op)
    return np.array(output)
call_output()

array([0.37688924, 0.81175838, 0.71685712, 0.67197753, 0.30123886])

In [119]:
call_output()

array([0.42395037, 0.91900049, 0.50595838, 0.42948086, 0.45399463])

array([0.38846305, 0.36462164, 0.34565417, 0.33173204, 0.32199998])